// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"program2","status":true,"description":"","parameters":{}},
{"name":"libtimidity","status":true,"description":"","parameters":{}},
{"name":"index","status":true,"description":"","parameters":{}},
{"name":"MIDIPlayer","status":true,"description":"","parameters":{}},
{"name":"XPWindowSKin","status":true,"description":"","parameters":{}},
{"name":"rgss","status":false,"description":"","parameters":{}},
{"name":"RGSSEnv","status":true,"description":"","parameters":{}},
{"name":"XPTilemap","status":true,"description":"","parameters":{}}
];
